FROM node:14.14.0-alpine
WORKDIR "/app"
COPY ./package.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "start"]

# docker build -f Dockerfile.dev .  --> build and install npm
# docker run __(docker_id_number)__  --> run app